Add 42-header modif to mvall

diff --git a/opt/bin/mvall b/opt/bin/mvall
--- a/opt/bin/mvall
+++ b/opt/bin/mvall
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# Abort if cmd fails
+set -e
 # Move all file matching pattern (given as first arg)
 if [ $# -lt 1 -o $# -gt 2 ]
 then
@@ -17,8 +19,9 @@ read answer
 if echo "$answer" | grep -iq "^y" ;then
 	for file_name in $1*
 	do
-		mv $file_name ${file_name/$1/$2}
+		new_file_name=${file_name/$1/$2}
+		mv $file_name $new_file_name
+		basename="${new_file_name##*/}"
+		sed -i "" "4s|\(/\* \{3\}\)\([a-z][^:]*\)\(\(:+: \{3,6\}\)\{3\}\*/\)|\1$(printf "%-51s" $basename)\3|" $new_file_name
 	done
-else
-	echo No
 fi
